development:
  adapter: mysql2
  encoding: utf8
  database: cfktracker
  username: root
  host: localhost
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: cfktracker_test
  username: root
  host: localhost
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_ADDRESS"] %>
  pool: 10
